### ISSUE TITLE
SublimeFiglet sopped working

### ISSUE THREAD

**Issue by mischnu** [adamchainz/SublimeFiglet#15]
Since yesterday, SublimeFiglet stopped working for me. Neither "Add Text" nor "Add Framed Comment" or even "Choose Font" will do anything.

Using Sublime Text 3.2.1 (Buld 3207) on latest macOS.

**Comment by adamchainz** [comment]
Oh yes, I upgraded pyfiglet in 9ee020ab3799d6dfa5e6e462682bd330bf66107e 2 days ago. I tried testing this with a locally symlinked version but now after installing from package manager I see:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "/Users/chainz/Library/Application Support/Sublime Text 3/Packages/Figlet Big ASCII Text/figlet.py", line 148, in run
    text = figlet_text(text)
  File "/Users/chainz/Library/Application Support/Sublime Text 3/Packages/Figlet Big ASCII Text/figlet.py", line 12, in figlet_text
    import pyfiglet
  File "/Users/chainz/Library/Application Support/Sublime Text 3/Packages/Figlet Big ASCII Text/pyfiglet/__init__.py", line 11, in <module>
    import pkg_resources
ImportError: No module named 'pkg_resource
```

I think I need to modify `pyfiglet` a bit!

**Comment by akudaniy** [comment]
Thanks for creating this issue. Yesterday I started to notice that Figlet suddenly not working. I did everything from reinstalled Figlet package, till reinstalled the whole Sublime editor. But none fixed the problem. I googled but none of the results said about Figlet's malfunction.

Hope the `pyfiglet` would be fixed soon.

> Since yesterday, SublimeFiglet stopped working for me. Neither "Add Text" nor "Add Framed Comment" or even "Choose Font" will do anything.
> 
> Using Sublime Text 3.2.1 (Buld 3207) on latest macOS.

**Comment by adamchainz** [comment]
I reverted the pyfiglet upgrade in 0dd4b39d40efb1ff51e7f7bdd26d939e1fac5c48 - after reinstalling it works again for me. Will try re-upgrade later.

**Comment by mischnu** [comment]
Great! A big **thanks** to you! 👍
